# Buildspec runs in the build stage of your pipeline.
version: 0.2
phases:
  build:
    commands:
      - echo "cd into $CODEBUILD_SRC_DIR"
      - cd $CODEBUILD_SRC_DIR
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $IMAGE_URL
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t java-repo .
      - "docker tag $REPO_NAME $IMAGE_URL/$REPO_NAME"
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image..
      - docker push $IMAGE_URL/$REPO_NAME
      - cd $CODEBUILD_SRC_DIR
      - echo Creating artifact..
      - docker run --rm -v $PWD:/mnt java-repo cp /application-assessment-repo/target/spring-petclinic-2.4.2.war /mnt/spring-petclinic-2.4.2.war
env:
  variables:
    AWS_ACCOUNT_ID: 052101902987
    AWS_DEFAULT_REGION: us-east-2
    CONTAINER_NAME: java
    IMAGE_URL: 052101902987.dkr.ecr.us-east-2.amazonaws.com
    REPO_NAME: java-repo:latest
artifacts:
  files:
    - spring-petclinic-2.4.2.war